### ISSUE TITLE
Kindly request the inclusion

### ISSUE THREAD

**Issue by Ahmedfrkh** [chawins/llm-sp#10]
Could you please add the following 2 privacy-related works? I believe they are very valuable. I would include them both under Privacy (subcategory: other). Thank you for maintaining this great repo!

- ObfuscaTune: Obfuscated Offsite Fine-tuning and Inference of Proprietary LLMs on Private Datasets: https://arxiv.org/abs/2407.02960
- IncogniText: Privacy-enhancing Conditional Text Anonymization via LLM-based Private Attribute Randomization: https://arxiv.org/abs/2407.02956

**Comment by chawins** [comment]
Added in this [commit](https://github.com/chawins/llm-sp/commit/da7963280e5efdda0c187b3f87d4631c089b4d95). Thanks for suggesting!
