### ISSUE TITLE
Kindly Request the Inclusion of My Work

### ISSUE THREAD

**Issue by XM-WANG** [chawins/llm-sp#2]
Hi,

Many thanks for your effort!  

This list contains numerous articles that I also find appealing, as well as some that I have not read yet but their titles have caught my interest.  May I kindly request the inclusion of my paper in the list? We proposed a new safety training method against jailbreak attacks, named Self-Guard. 

- Title: Self-Guard: Empower the LLM to Safeguard Itself
- Link: https://arxiv.org/abs/2310.15851

We have restructured the paper based on the current preprint version, adding new experimental results, including ablation experiments. Unfortunately, due to the anonymity period, I am unable to update the preprint version in time. Although the publicly available version of our work is not perfect at present, please rest assured that we have made numerous updates, and we believe it will be beneficial to the LLM safety community. We will promptly update our paper once the anonymity period is lifted. My only wish is for my paper to be included in such a splendid list, not to promote it.

Of course, I am merely seeking your consent. Please do not feel pressured, as you are entirely free to decline my request and colse this issue. Regardless of the results, we will continue to refine our work. 

Once again, I would like to express my gratitude for your efforts and contributions.

Best,
Zezhong

**Comment by chawins** [comment]
Thanks for the suggestion! It seems like the approach has two components, but I added it under the guardrail defense section for now. I also added a tldr based on the abstract, but please feel free to provide your own version if you'd like to. It will surely be better than the one I have now :)

**Comment by XM-WANG** [comment]
Thanks for including our work in your list! Your recognition is greatly appreciated.

Regarding the TL;DR section, I would like to propose a slightly revised version for your consideration. I understand that brevity is key, so if you find the revision to be lengthy, you may wish to retain only the first sentence (in **bold**).

>**To counter jailbreak attacks, this work proposes a new safety method, Self-Guard, combining the advantages of safety training and safeguards.** The method trains the LLM to always append a [harmful] or [harmless] tag to the end of its response before replying to users. In this way, a basic filter can be employed to extract these tags and decide whether to proceed with the response.

I would like to extend my sincere gratitude once again for your dedication and sharing. 😄

**Comment by chawins** [comment]
Of course! Just added the suggested description. Thanks!
