### ISSUE TITLE
Kindly Request the Inclusion

### ISSUE THREAD

**Issue by SheltonLiu-N** [chawins/llm-sp#4]
Hi Chawin,

Just wanted to say a big thanks for all the awesome stuff you've been doing for the community. Your recent paper on the black-box jailbreaking attack was super interesting – really enjoyed reading it!! It's really excited to see that the hybrid attacks (combining query-based + proxy models) remain effective in jailbreaking.

I was wondering if you might take a look at our paper and add to your list, "[AutoDAN: Generating Stealthy Jailbreak Prompts on Aligned Large Language Models](https://arxiv.org/abs/2310.04451)." It's a ICLR24 paper and not exactly new, but it's been doing well in some of the open-source benchmarks, like CAIS's [Harmbench](https://www.harmbench.org/).

Thanks a ton for considering it. Looking forward to any opportunity to chat more!

**Comment by chawins** [comment]
Thank you for the kind words. I somehow missed your paper; I actually have read it a while ago, and I love it! I have added it in the Notion; I will transfer it to GitHub now. Congrats on writing a great paper and on the ICLR acceptance.
