### ISSUE TITLE
Kindly request the inclusion

### ISSUE THREAD

**Issue by xirui-li** [chawins/llm-sp#5]
I'm reaching out to share a recent paper I've co-authored titled "DrAttack: Prompt Decomposition and Reconstruction Makes Powerful LLM Jailbreakers". Our research focuses on jailbreaking LLM by prompt decomposition, and I believe it aligns well with your interest in LLM safety.

You can access the paper [here](https://arxiv.org/abs/2402.16914). Our [project page](https://xirui-li.github.io/DrAttack/) and [twitter message](https://x.com/XIRUILI482905/status/1762996532926947659?s=20) are also available for your reference.

Thank you so much for considering my request. I'm also open to any questions or discussions this might spark – I'd love to engage in a meaningful conversation with someone of your expertise.

Best regards,
Xirui Li

**Comment by chawins** [comment]
Thank you for point me to this paper! I will surely have a look. I will add it in the list now, but please let me know if you would like to provide your own summary of the paper.
