### ISSUE TITLE
Kindly Add a recent work

### ISSUE THREAD

**Issue by zichuan-liu** [chawins/llm-sp#6]
Hi, I would like to add our completed paper from MSFT Research about defense against adversarial attacks, "Protecting Your LLMs with Information Bottleneck" [paper](https://arxiv.org/pdf/2404.13968.pdf) , thanks!

**Comment by chawins** [comment]
Sure! Thank you for point out the paper; looks very interesting!
I will push it up for now, but please feel free to do a PR (or just let me know here) if you want to add your own summary.
